name: portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #dart
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  lottie: ^3.1.2
  flutter_bloc: ^9.1.0


  dartz: ^0.10.1
  injectable: ^2.5.0
  url_launcher: ^6.3.1

  #app specific settings
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.1
#  flutter_native_splash: ^2.4.3
  change_app_package_name: ^1.3.0
  carousel_slider: ^5.0.0
  syncfusion_flutter_pdfviewer: ^29.1.40

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner:
  json_serializable: ^6.8.0
  injectable_generator:

  flutter_oss_licenses: ^3.0.2

flutter_gen:
  output: lib/common/resources/gen
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/fonts/
    - assets/animations/
    - assets/image/svg/
    - assets/image/png/
    - assets/translations/
    - assets/files/
    - assets/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 100
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 500
        - asset: assets/fonts/IBM-Medium.ttf
          weight: 300
        - asset: assets/fonts/IBM-Medium.ttf
          weight: 400
        - asset: assets/fonts/IBM-Medium.ttf
          weight: 100


#flutter_native_splash:
#  color: "#0E2954"
#  image: assets/image/png/me.jpeg
#  android_12:
#    color: "#0E2954"
#    image: assets/image/png/me.jpeg
#    icon_background_color: "#0E2954"
#  android: true
#  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/image/png/me.jpeg"
  adaptive_icon_background: "#0E2954"
  min_sdk_android: 24
  image_path: "assets/image/png/me.jpeg"
  adaptive_icon_padding: true